# Generated by Django 4.2.3 on 2024-01-16 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_quantity', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Success'), (1, 'Pending')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='categorytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='giftstockisttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('phone_no', models.IntegerField()),
                ('address', models.TextField(max_length=40)),
                ('stockist_image', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='ordertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=10)),
                ('total_amount', models.FloatField()),
                ('order_status', models.IntegerField(choices=[(0, 'Delivered'), (1, 'Pending')], default=1)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.carttable')),
            ],
        ),
        migrations.CreateModel(
            name='paymenttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.BigIntegerField()),
                ('payment_status', models.IntegerField(choices=[(0, 'Success'), (1, 'Failed')])),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.ordertable')),
            ],
        ),
        migrations.CreateModel(
            name='usertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20)),
                ('u_email', models.CharField(max_length=20)),
                ('u_password', models.CharField(max_length=25)),
                ('u_phone', models.BigIntegerField()),
                ('u_status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='userdeatiltable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('u_address', models.TextField()),
                ('u_image', models.ImageField(upload_to='photos')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='returnproducttablr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_return', models.DateField()),
                ('return_status', models.IntegerField(choices=[(0, 'Returned'), (1, 'Processing')])),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.ordertable')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.paymenttable')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='producttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=15)),
                ('p_description', models.CharField(max_length=25)),
                ('p_image', models.ImageField(upload_to='photos')),
                ('p_quantity', models.IntegerField()),
                ('p_price', models.BigIntegerField()),
                ('p_status', models.IntegerField(choices=[(0, 'Available'), (1, 'Not Available')], default=0)),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.categorytable')),
                ('stockist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.giftstockisttable')),
            ],
        ),
        migrations.AddField(
            model_name='paymenttable',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.usertable'),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.usertable'),
        ),
        migrations.CreateModel(
            name='feedbacktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.producttable')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='complaintable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('complain_status', models.IntegerField(choices=[(0, 'Solved'), (1, 'Pending')])),
                ('complain_date', models.DateField()),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.usertable')),
            ],
        ),
        migrations.AddField(
            model_name='carttable',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.producttable'),
        ),
        migrations.AddField(
            model_name='carttable',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.usertable'),
        ),
        migrations.CreateModel(
            name='cardtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=20)),
                ('cvv', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('card_number', models.BigIntegerField()),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.usertable')),
            ],
        ),
    ]
