# Generated by Django 4.2.3 on 2024-01-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='returnproducttablr',
            new_name='returnproducttable',
        ),
    ]
