# Generated by Django 4.2.3 on 2024-01-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0003_remove_userdeatiltable_u_image_usertable_u_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='u_image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
