# Generated by Django 4.2.3 on 2024-02-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0005_usertable_u_type_alter_producttable_stockist_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='u_type',
            field=models.CharField(max_length=10),
        ),
    ]
