# Generated by Django 4.2.3 on 2024-02-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0006_alter_usertable_u_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='comments',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usertable',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='usertable',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
