# Generated by Django 4.2.3 on 2024-02-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0007_usertable_comments_usertable_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='dob',
            field=models.DateField(),
        ),
    ]
