# Generated by Django 4.2.3 on 2024-02-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0008_alter_usertable_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='u_address',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='userdeatiltable',
        ),
    ]
