# Generated by Django 4.2.3 on 2024-02-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0010_alter_categorytable_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.producttable')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.usertable')),
            ],
        ),
    ]
