# Generated by Django 4.2.3 on 2024-02-15 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0012_remove_carttable_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='multipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_image', models.ImageField(upload_to='')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.producttable')),
            ],
        ),
    ]
