# Generated by Django 4.2.3 on 2024-02-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0013_multipleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimage',
            name='p_image',
            field=models.FileField(upload_to=''),
        ),
    ]
