# Generated by Django 4.2.3 on 2024-02-16 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0014_alter_multipleimage_p_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HamperTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hamper_name', models.CharField(max_length=200)),
                ('hamper_price', models.IntegerField()),
                ('hamper_image', models.ImageField(upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftapp.usertable')),
            ],
        ),
    ]
