# Generated by Django 4.2.3 on 2024-02-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0015_hampertable'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttable',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
