# Generated by Django 4.2.3 on 2024-02-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0016_carttable_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacktable',
            name='review_name',
            field=models.CharField(default='Default Review Name', max_length=150),
        ),
    ]
