# Generated by Django 4.2.3 on 2024-02-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0018_multiplefeedbackimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacktable',
            name='submit_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
