# Generated by Django 4.2.3 on 2024-02-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0020_alter_complaintable_complain_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintable',
            name='complain_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
